blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('blogApp.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/blogApp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blogApp/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path('post/<str:slug>', detail, name='details'),
    path('contact', contact_view, name='contact'),
    path('about', About, name='about'),
    path('register', register, name='register'),

    path('login/', login, name='login'),
    path('logout', logout, name='logout'),
    path('dashboard',dashboard, name='dashboard'),
    # path('password_reset', forgotpwd, name='forgotPassword'),
    # path('reset_password/<uidb64>/<token>', reset_password, name='reset_password'),
    path('new-post', newpost.as_view(), name='newpost'),
    path('edit-post/<str:slug>', editpost.as_view(), name='editpost'),
    path('delete-post/<str:slug>/', delete_post, name='delete_post'),
]

blogApp/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

#catagory
class Catagory(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    img_url = models.ImageField(null=True, blank=True, upload_to='posts/images')
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    catagory = models.ForeignKey(Catagory, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.img_url:
            self.img_url = 'https://upload.wikimedia.org/wikipedia/commons/1/14/No_Image_Available.jpg'
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    @property
    def formatted_imag_url(self):
        url = self.img_url if self.img_url.__str__().startswith(('http://','https://')) else self.img_url.url
        return url

    def __str__(self):
        return self.title

class AboutUs(models.Model):
    content = models.TextField()

blogApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from blogApp.models import Catagory, Post

class ContactForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, required=True)
    email = forms.EmailField(label = 'Email', required=True)
    message = forms.CharField(label='Message', required=True)

class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='Username', max_length=100, required=True)
    email = forms.EmailField(label='Email', max_length=100, required=True)
    password = forms.CharField(label='Password', max_length=100, required=True)
    password_confirm = forms.CharField(label='Confirm Password', max_length=100, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean(self):
        cData = super().clean()
        pwd = cData.get('password')
        cPwd = cData.get('password_confirm')

        if pwd:
            if len(pwd)<6:
                raise forms.ValidationError('Minimum Length of Password must be 6')
            if not any(i in '!@#$%^&*()_+-' for i in pwd):
                raise forms.ValidationError('Password must Contain at leat one Special Character')
            if not any(i.isupper()  for i in pwd):
                raise forms.ValidationError('Password must Contain at leat one UpperCase')
            if not any(i.islower()  for i in pwd):
                raise forms.ValidationError('Password must Contain at leat one UpperCase')
            if pwd != cPwd:
                raise forms.ValidationError('Confirm Password do not Match')
        
class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=100, required=True)
    password = forms.CharField(label='Password', max_length=100, required=True)

    def clean(self):
        cData = super().clean()
        username = cData.get('username')
        pwd = cData.get('password')
        if username and pwd:
            user = authenticate(username=username, password=pwd)
            if user is None:
                raise forms.ValidationError('Username or Password is Wrong')

class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=250, required=True)

    def clean(self):
        cData = super().clean()
        email = cData.get('email')

        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('No user register with this Email.')

class ResetPasswordForm(forms.Form):
    npwd = forms.CharField(label='New Password', min_length=6, required=True)
    cpwd = forms.CharField(label='Confirm Password', min_length=6, required=True)

    def clean(self):
        cData = super().clean()
        new_password = cData.get('npwd')
        confirm_password = cData.get('cpwd')

        if new_password:
            if len(new_password) < 6:
                raise forms.ValidationError('Minimum Length of Password must be 6')
            if not any(i in '!@#$%^&*()_+-' for i in new_password):
                raise forms.ValidationError('Password must contain at least one special character')
            if not any(i.isupper() for i in new_password):
                raise forms.ValidationError('Password must contain at least one uppercase letter')
            if not any(i.islower() for i in new_password):
                raise forms.ValidationError('Password must contain at least one lowercase letter')
            if new_password != confirm_password:
                raise forms.ValidationError('Confirm Password does not match')
            
# class PostForm(forms.ModelForm):
#     title = forms.CharField(label='Title', max_length=200, required=True)
#     Content = forms.CharField(label='Content')
#     catagory = forms.ModelChoiceField(label='Catagory', required=True, queryset=Catagory.objects.all())

#     class Meta:
#         model = Post
#         fields = ['title', 'content', 'catagory', 'img_url']

#     def clean(self):
#         cData = super().clean()
#         title = cData.get('title')
#         con

#         if title and len(title)<5:
#             raise forms.ValidationError('The length of Title must be 5 Character.')
        
#         if content and len(content)<10:
#             raise forms.ValidationError('The length of Content must be 10 Character.')

blogApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import logging
from .models import Catagory, Post, AboutUs
from django.core.paginator import Paginator
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.core.mail import send_mail

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    blog_title = 'Latest Posts'
    all_posts = Post.objects.all()

    # Paginate
    paginator = Paginator(all_posts, 5)
    page_no = request.GET.get('page')
    page_object = paginator.get_page(page_no)

    return render(request, 'index.html', {'blog_title':blog_title, 'page_obj':page_object})

def detail(request, slug):
    post = Post.objects.get(slug = slug)
    related_posts = Post.objects.filter(catagory = post.catagory).exclude(pk=post.pk)
    # logger = logging.getLogger('TESTING')
    # logger.debug(f'post variable is {post}')
    return render(request, 'detail.html', {'post':post, 'related_posts':related_posts})

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        if form.is_valid():
            success_message = 'Your Email has been Send!'

            #Write Code For database
            #

            return render(request, 'contact.html', {'form':form, 'success_message':success_message})
        return render(request, 'contact.html', {'form':form, 'name':name, 'email':email, 'message':message})
    return render(request, 'contact.html')


def About(request):
    about = AboutUs.objects.first()
    if about is None or not about.content:
        about = 'There is no Content About Us'
    else:
        about = about.content
    return render(request, 'about.html', {'about_content':about})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            messages.success(request, 'Registration Successfull, You can Login Now!')
            return redirect('blog:login')
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form':form})

def login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('blog:dashboard')
    return render(request, 'login.html', {'form':form})

def dashboard(request):
    blogTitle = 'My Posts'
    # getting User Post
    all_posts = Post.objects.filter(user=request.user)

    # Paginate
    paginator = Paginator(all_posts, 5)
    page_no = request.GET.get('page')
    page_object = paginator.get_page(page_no)

    return render(request, 'dashboard.html', {'blogTitle':blogTitle, 'page_obj':page_object})

def logout(request):
    auth_logout(request)
    return redirect('blog:index')

# def forgotpwd(request):
#     form = ForgotPasswordForm() 
#     if request.method == 'POST':
#         form = ForgotPasswordForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data['email']
#             user = User.objects.filter(email=email)

#             #send email to reset email
#             token = default_token_generator.make_token(user)
#             uid = urlsafe_base64_encode(force_bytes(user.pk))
#             site = get_current_site(request)
#             domain = site.domain
#             subject = 'Reset Password Requested'
#             message = render_to_string('reset_password_email.html', {'domain':domain, 'uid':uid, 'token':token})
#             send_mail(subject, message, 'noreply@sivaguru.com', [email])
#             messages.success(request, 'Email has been sent successfully!')

#     return render(request, 'forgotpwd.html', {'form':form})
    
# def reset_password(request, uidb64, token):
#     form = ResetPasswordForm()
#     if request.method == 'POST':
#         form = ResetPasswordForm(request.POST)
#         if form.is_valid():
#             new_password = form.cleaned_data['new_password']
#             uid = urlsafe_base64_decode(uidb64)
#             try:
#                 user = User.objects.get(pk=uid)
#             except(TypeError, ValueError, OverflowError, User.DoesNotExist):
#                 user = None

#             if user is not None and default_token_generator.check_token(user, token):
#                 user.set_password(new_password)
#                 user.save()
#                 messages.success(request, 'Your passwoard has been reset successfully!')
#                 return redirect('blog:login')
#             else:
#                 messages.error(request, 'The passward reset link is Invalid')

#     return render(request, 'reset_password.html', {'form':form})

# def newpost(request):
#     catagories = Catagory.objects.all()
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.user = request.user
#             post.save()
#             messages.success(request, "Post created successfully!")
#             return redirect('blog:dashboard')
#     else:
#         form = PostForm()
#     return render(request, 'newpost.html', {'catagories':catagories, 'form':form})

class newpost(LoginRequiredMixin, CreateView):
    model = Post
    fields = '__all__'
    success_url = reverse_lazy('blog:dashboard')
    template_name = 'newpost.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, 'Post Created successfully! ✅')
        return super(newpost, self).form_valid(form)
    
class editpost(LoginRequiredMixin, UpdateView):
    model = Post
    fields = '__all__'
    template_name = 'editpost.html'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_success_url(self):
        return reverse_lazy('blog:dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, 'Post updated successfully! ✅')
        return super(editpost, self).form_valid(form)
    
@csrf_exempt
@login_required
def delete_post(request, slug):
    if request.method == "POST" and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        try:
            post = Post.objects.get(slug=slug, user=request.user)
            post.delete()
            return JsonResponse({'status': 'success'})
        except Post.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Post not found'})
    return JsonResponse({'status': 'error', 'message': 'Invalid request'})

blogApp/templates/about.html
{% extends "base.html" %}

{% block 'content' %}
    <div class="container-fluid ">
        <h3>About Us</h3>
        <div class="d-flex gap-3 justify-content-center mt-5">
            <img src="https://picsum.photos/300/300" alt="">
            <div class="content">
            </div>
            {{about_content}} 
        </div>
    </div>
{% endblock 'content' %}

blogApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Guru Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >
    <header class="p-3 bg-dark text-white">
        <div class="row">
            <div class="col">
                <a class='text-light text-decoration-none'  href='/'><h3>Blog</h3>
            </div>
            <div class="col">
                <div class="d-flex justify-content-center gap-3">
                    <a class="text-light text-decoration-none" href="/">Home</a>
                    <a class="text-light text-decoration-none" href="{% url "blog:about" %}">About</a>
                    <a class="text-light text-decoration-none" href="{% url 'blog:contact' %}">Contact</a>
                    {% if user.is_authenticated  %}
                    <a class="text-light text-decoration-none" href="{% url 'blog:dashboard' %}">Dashboard</a>
                    <a class="text-light text-decoration-none" href="{% url 'blog:logout' %}">Logout</a>
                    {% else %}
                    <a class="text-light text-decoration-none" href="{% url 'blog:login' %}">Login</a>
                    <a class="text-light text-decoration-none" href="{% url 'blog:register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
  
    {% block 'content' %}
    {% endblock%}

    <footer class="bg-dark text-light p-3">
        <div class="col-4 d-flex justify-content-center align-items-center">
          <span class="text-light">© 2021 Company, Inc</span>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

blogApp/templates/contact.html
{% extends "base.html" %}

{% block  'content'%}
    <div class="container-fluid ">
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex gap-3 flex-column">
                <h3>Contact Form</h3>
                <!-- Error Message -->
                {% for field in form %}
                {% if field.errors %}
                    <div class="col-12">
                        <span class="fw-bold">{{field.label_tag}}</span>
                        {% for error in  field.errors %}
                            <span class="text-danger">{{error}}</span>
                        {% endfor %}
                    </div>
                {% endif %} 
                {% endfor %}

                <!-- success Message -->
                {% if success_message %}
                    <div class='alert alert-success' role='alert'>
                        {{success_message}}
                    </div>
                {% endif %}
                
                <form method="post" class="row g-3">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value='{{name}}'>
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email" value='{{email}}'>
                    </div>
                    <div class="col-12">
                        <label for="message" class="form-label">Message</label>
                        <textarea class="form-control" id="message" name="message" rows="4" value='{{message}}'></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
{% endblock  %}

blogApp/templates/dashboard.html
{% extends "base.html" %}

{% block 'content' %}
<div class="container-fluid">
  <div class="row">
    <div class="col-6">
      <h3>Hi, {{user.username}}</h3>
    </div>
    <div class="col d-flex justify-content-end">
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-6">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>

  <div class="row">
    <h2 class="mt-3">{{blogTitle}}</h2>
    <div class="d-flex justify-content-center">
      <a href="{% url 'blog:newpost' %}" class="btn btn-success">New Post</a>
    </div>
  </div>

  <div class="row m-3">
    {% if page_obj %}
      {% for post in page_obj %}
      <div class="col-4 mb-4" id="post-{{ post.slug }}">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-md-4">
                <img style="height:100px; width:150px;" src="{{ post.formatted_imag_url }}" class="img-fluid" alt="Post_image">
              </div>
              <div class="col-md-8">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.content | truncatechars:45 }}</p>
                <div class="d-flex justify-content-between">
                  <a href="{% url 'blog:details' slug=post.slug %}">Read More</a>
                  <a class="text-decoration-none text-dark fw-bold" href="#">{{ post.catagory.name }}</a>
                </div>
                <div class="d-flex justify-content-between mt-2">
                  <a class="btn btn-warning" href="{% url 'blog:editpost' slug=post.slug %}">Edit post</a>
                  <form id="delete-form-{{ post.slug }}" onsubmit="deletePost(event, '{{ post.slug }}')" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}

      <div class="col-12 my-3">
        {% if page_obj.has_other_pages %}
        <nav aria-label="Page navigation">
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>
            {% endif %}
            <li class="page-item disabled"><span class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span></li>
            {% if page_obj.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
            {% endif %}
          </ul>
        </nav>
        {% endif %}
      </div>
    {% else %}
      <p>No Post Created</p>
    {% endif %}
  </div>
</div>

<script>
  function getCSRFToken() {
    return document.querySelector('[name=csrfmiddlewaretoken]').value;
  }

  function deletePost(event, slug) {
    event.preventDefault();

    if (confirm("Are you sure you want to delete this post?")) {
      fetch(`/delete-post/${slug}/`, {
        method: 'POST',
        headers: {
          'X-CSRFToken': getCSRFToken(),
          'X-Requested-With': 'XMLHttpRequest',
        }
      })
      .then(response => response.json())
      .then(data => {
        if (data.status === 'success') {
          const postCard = document.getElementById(`post-${slug}`);
          postCard.style.transition = 'opacity 0.5s';
          postCard.style.opacity = 0;
          setTimeout(() => postCard.remove(), 500);
        } else {
          alert(data.message || "Error deleting post.");
        }
      })
      .catch(error => {
        console.error('Error:', error);
        alert("Something went wrong.");
      });
    }
  }

  setTimeout(function () {
    const msgContainer = document.getElementById("message-container");
    if (msgContainer) {
      msgContainer.style.display = 'none';
    }
  }, 3000);

</script>
{% endblock %}

blogApp/templates/detail.html
{% extends "base.html" %}
{% block 'content' %}
<div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">{{post.title}} <small style='font-size:20px'>({{post.catagory.name}})</small></h1>
              <p class="text-muted">Posted on {{post.created_at | date:'F j, Y'}}</p>
              <img src="{{post.formatted_imag_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    {% for related_post in related_posts%}
                    <li><a href="{% url 'blog:details' slug=related_post.slug %}">{{related_post.title}}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
        </div>
    </div>

{% endblock 'content' %}

blogApp/templates/index.html
{% extends "base.html" %}

{% block 'content' %}
<div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <h2 >{{blog_title | upper}}</h2>
            </div>
            <div class="col-3"> 
                {% comment %} <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                    <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                      <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                    </button>
                  </div> {% endcomment %}
            </div>
        </div>
        <div class="row m-3">
            {% for post in page_obj %}
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img style='height:300; width:300;' src="{{post.formatted_imag_url}}" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">{{post.content | truncatechars:45}}</p>
                                <div class="d-flex justify-content-between">
                                     <a href="{% url 'blog:details' slug=post.slug %}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{post.catagory.name}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div class="col-12 my-3">
                {% if page_obj.has_other_pages %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                        {% endif %}
                        <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                        {% if page_obj.has_next%}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                {% endif %}
            </div>
        </div>
        <div class="row">
        </div>
        
    </div>
{% endblock %}

blogApp/templates/login.html
{% extends "base.html" %}

{% block 'content' %}
    <div class="container-fluid">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-4">
                <h3>Login</h3>
                <div class="">
                 {% include "error.html" %}
                </div>

                <div class="my-3">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username" class="form-label">Username</label>
                            <input type="text" class="form-control" id="username" name="username" value="{{form.username.value | default:''}}">
                        </div>
                       
                        <div class="form-group">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                       
                        <div class="my-3 d-flex justify-content-between">
                            {% comment %} <a href="{% url 'blog:forgotPassword' %}">Forgot Password</a> {% endcomment %}
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                    <p> If You don't have account, <a href='{% url "blog:register" %}'> Register</a> here</p>
                </div>
            </div>
        </div>
    </div>
{% endblock 'content' %}